modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="simple_tuff"
version="1.0.0"
displayName="Simple Tuff Mod"
displayURL="https://modrinth.com/project/simple-tuff-mod"
logoFile="logo.png"
credits="Created with MCreator"
authors="Conteek"
description="Mod adding tuff blocks from version 1.21 for Minecraft 1.20 and below"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.simple_tuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



